### ISSUE TITLE
Error with google account access

### ISSUE THREAD

**Issue by ivanoterouvigo** [up2university/single-sign-on#48] opened 2018-11-19 00:49 UTC
Hi everyone!

A teacher who attended Italian training course in april/may has a problem accessing the course.

He autenticated to the platform and created an account using his google account at the beginning of the training course. He followed the course and now he wants to consult its materials again, but he can't.
The error that appear is an "unhandled exception", with the following tracking id

b07fe95c83

How can we solve the problem?

Regards

**Comment by foobarable** [comment] 2018-11-19 15:05
@m0ark @michzimny Waiting for response from our IDM team to fix this issue

**Comment by foobarable** [comment] 2018-11-20 09:47
@ivanoterouvigo Can you try again?

**Comment by foobarable** [comment] 2018-11-27 12:49
Is this problem still existent?

**Comment by ivanoterouvigo** [comment] 2019-01-08 18:12
Hi @foobarable @michzimny,

We get again the same issue from Italian teachers 

The error generated is always the same 
(exception not menaged - or something like that-, tracking id b07fe95c8).

I received this error **on 7 of January** but the person who told me the error received the error **on 28 of December**.
So I am the third person in to receive this email.
This error happen in the test platform. https://learn.test.up2university.eu

But, today this afternoon I had a webwinar with some teachers and the get the same error in the production platform.

This one of the errors
(exception not menaged , tracking id 9127a0f4fa).

So I think this is a critical issue, we need to solve as quickly as possible.
At least discovering What is the problem or What are the actions that produce this errors.

Regards

**Comment by foobarable** [comment] 2019-01-09 08:37
We will have a look at it.

**Comment by foobarable** [comment] 2019-01-09 08:47
@ivanoterouvigo It looks like the problem is that multiple accounts with the same attributes exist, which we currently can not fix. Did you, by any means, register one account with a gmail address and then try to access the sso via google authentication?

**Comment by foobarable** [comment] 2019-01-09 08:50
Also, can you send me the mail-adresses of the teachers affected?

**Comment by ivanoterouvigo** [comment] 2019-01-09 09:51
Hi @foobarable, sorry I don't have your email, and you don't have your email on your profile.
Could you send me this information?

**_Situation 1)_** Related with this case **tracking id b07fe95c8**  yes there is multiple email for the same email account.
This is the case for the Italian teacher.

But the best workaround I suggest is:

If you login with Social Media, for example facebook and you logged in some days before with Social Media for example Google account as the first time. 

Then the system need to check if the account exist and after that show to users.  

Sorry, your email exist in our platform. 
Do you want to know in which way do you logged? Type your email here.

**_Situation 2)_** Related with this case **tracking id 9127a0f4fa** 
In this case this teacher has only one account.
So I didn't understand what could be the problem here.

Anyway, I would need access to >> site administration,  >> reports, >> logs
in order to know more about this issues.

So, I hope your email to send more details about.
Thanks in advance

**Comment by michzimny** [comment] 2019-01-09 15:12
> @ivanoterouvigo It looks like the problem is that multiple accounts with the same attributes exist, which we currently can not fix. Did you, by any means, register one account with a gmail address and then try to access the sso via google authentication?

@foobarable, if this is a case that we cannot solved, then we need to do everything to prevent users from reaching such a state. For instance, by blocking the second authentication when the first account already exists.

**Comment by foobarable** [comment] 2019-01-11 12:14
We have this logic already implemented. We first perform an LDAP search and check, if the user is already present. But in this case, the LDAP search returned an error which triggered our logic (correctly) to create a new account. We still investigate what the problem with the ldap search was.

**Comment by michzimny** [comment] 2019-01-11 13:54
Thanks for this update. Is the logic correct that it allows to create an account once it knows that there is an error with the backend ldap (i.e. the search query failed)?

**Comment by foobarable** [comment] 2019-01-11 14:10
The search query didn't fail, it returned with "no such user". But the user was there. We currently think it was a replication issue. But can't say for sure.

**Comment by ivanoterouvigo** [comment] 2019-02-08 08:53
Hi everyone,
@michzimny , @foobarable 

I met yesterday with a Spanish teacher in order to help him with the moodle platform.
I told him to login here. learn.up2university.eu **(MPP)**
Here you are.

![error_sso_emilio_v000-pixel](https://user-images.githubusercontent.com/11814769/52467628-80524c80-2b86-11e9-8260-f8c7262e9f65.png)


![error_sso_emilio_v001-pixel](https://user-images.githubusercontent.com/11814769/52467636-8811f100-2b86-11e9-871f-34d73467e52e.png)


![error_sso_emilio_v002](https://user-images.githubusercontent.com/11814769/52467640-8c3e0e80-2b86-11e9-81d0-9dbd774ee825.png)

![error_sso_emilio_v003-pixel](https://user-images.githubusercontent.com/11814769/52467648-9233ef80-2b86-11e9-90d6-8e68430eb870.png)

It is the second time It happenned to me.
The last time I reported this 1 month ago.

So the error message didn't change.

Regards

**Comment by foobarable** [comment] 2019-02-11 12:45
Should be fixed for now. Please tell me if you experience similar issues again.

**Closed by foobarable** 2019-02-11 12:45 UTC
Labels: critical
