### ISSUE TITLE
SSO requests for uid attribute

### ISSUE THREAD

**Issue by michzimny** [up2university/single-sign-on#25] opened 2018-03-09 13:13 UTC
@misi reports:

> I have an issue with edugain login:
> 
![37207616-0edd96e0-239e-11e8-9a43-f5f1f76e3747 1](https://user-images.githubusercontent.com/1483196/37209015-d7150620-23a3-11e8-8e41-23b1987ea7ee.png)
> According our AAI team:
> *  edupersonTargetedId is Ok. (they will fix it.)
>  but
> * uid: A well configured IdP don't expose the uid attribute. (never ever)
>    Why do you require this attribute?

**Comment by foobarable** [comment] 2018-03-09 13:15
It's either eduPersonTargetedID or uid. So if you send ePTID it's fine. (Uid is just for google auth)

**Comment by misi** [comment] 2018-03-09 13:25
@foobarable 
Ok now I see THX.


Would it be possible to add your SP "R&S entitycategory"?
Then all IdP would by default release eduPersonTargetedID.
If not then all IdP must one by one may needed to set an exception to release this attribute.

Look forward to hear about Your thoughts on this...

**Comment by foobarable** [comment] 2018-03-09 13:33
Yes, we can supply a CoCo and join the R&S category. You are right, we should do that.

**Comment by foobarable** [comment] 2018-03-16 13:31
@misi DFN now set this flag and the R&S category will be in the metadata for this SP after the weekend.

**Comment by misi** [comment] 2018-03-21 12:37
Unfortunately I still get the same error.

It is still not in metadata in mds.geant.org.
I still couldn't find R&S..
:(

`
<saml:AttributeValue>http://refeds.org/category/research-and-scholarship</saml:AttributeValue>`

**Comment by foobarable** [comment] 2018-03-21 12:39
Have to proxy this to DFN, I just forwarded what I was told. Stay tuned

**Comment by misi** [comment] 2018-03-21 12:41
@foobarable According it could you please reopen this issue?

**Comment by foobarable** [comment] 2018-03-21 13:58
This is how the metadata look in the dfn aai. So it looks like they are not propagated to edugain? 

```<EntityDescriptor entityID="https://sso.test.up2university.eu/ssp">
<Extensions>
<mdrpi:RegistrationInfo registrationAuthority="https://www.aai.dfn.de" registrationInstant="2018-02-28T14:54:23Z">
<mdrpi:RegistrationPolicy xml:lang="en">https://www.aai.dfn.de/en/join/</mdrpi:RegistrationPolicy>
<mdrpi:RegistrationPolicy xml:lang="de">https://www.aai.dfn.de/teilnahme/</mdrpi:RegistrationPolicy>
</mdrpi:RegistrationInfo>
<mdattr:EntityAttributes>
<saml:Attribute Name="http://macedir.org/entity-category" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
<saml:AttributeValue>
http://refeds.org/category/research-and-scholarship
</saml:AttributeValue>
</saml:Attribute>
</mdattr:EntityAttributes>
</Extensions>```

**Comment by foobarable** [comment] 2018-03-21 14:04
Metadata from mds.edugain.org:

<md:EntityDescriptor entityID="https://sso.test.up2university.eu/ssp">
    <md:Extensions>
      <mdrpi:RegistrationInfo registrationAuthority="https://www.aai.dfn.de" registrationInstant="2018-02-28T14:54:23Z">
        <mdrpi:RegistrationPolicy xml:lang="en">https://www.aai.dfn.de/en/join/</mdrpi:RegistrationPolicy>
        <mdrpi:RegistrationPolicy xml:lang="de">https://www.aai.dfn.de/teilnahme/</mdrpi:RegistrationPolicy>
      </mdrpi:RegistrationInfo>
      <mdattr:EntityAttributes>
        <saml:Attribute Name="http://macedir.org/entity-category" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
          <saml:AttributeValue>http://refeds.org/category/research-and-scholarship</saml:AttributeValue>
        </saml:Attribute>
      </mdattr:EntityAttributes>
    </md:Extensions>

**Comment by foobarable** [comment] 2018-03-21 14:04
Looks right to me

**Comment by foobarable** [comment] 2018-03-21 14:08
Ah, I found the issue, we currently just did it for the test system.

**Comment by foobarable** [comment] 2018-03-21 14:10
We now did it for the production system. Will take a while till metadata propagate, though.

**Comment by misi** [comment] 2018-03-21 14:15
Could you also add coco too?

**Comment by misi** [comment] 2018-03-21 14:29
No coco is not needed. Sorry...

**Comment by misi** [comment] 2018-03-21 14:39
1. I mixed an older and the actual eduGain metadata. This is why I saw that sso.test don't have R&S.
Sorry! (user error)

2.You are right the problem was that https://learn.test.up2university.eu/ is using and sso.up2u and it don't have R&S

Is it by design that test moodle does not use the test sso? 
It seems for me little bit confusing.

**Comment by michzimny** [comment] 2018-03-21 15:44
Please have a look at https://wiki.geant.org/display/UP2U/Moodle+instances for clarification on our Moodle instances.

**Comment by misi** [comment] 2018-03-22 06:52
@michzimny thx for the info about moodle.
Now works fine with the updated metadata. 
THX for your help!

**Comment by foobarable** [comment] 2018-03-23 15:39
@misi Can we close the issue then?

**Comment by misi** [comment] 2018-03-23 18:49
Yes many thanks

Az Android készülékemrõl küldtem.

-----Original Message-----

**Closed** 2018-04-16 09:13 UTC
Labels: critical
